= Gupta Real Estate

The website for First Team's Gupta Realty, built through Kotlin Multiplatform with a Kobweb frontend and an http4k backend.

As a template configurable through the application itself or through code, feel free to use this project as a basis for your own site. The template for this own project, including the unique tech stack, can be found at https://github.com/OmyDaGreat/DynamicSiteTemplate[DynamicSiteTemplate]. Feel free to contribute!

image:https://img.shields.io/badge/kotlin-%237F52FF.svg?style=for-the-badge&logo=kotlin&logoColor=white[Kotlin] image:https://img.shields.io/badge/docker-%230db7ed.svg?style=for-the-badge&logo=docker&logoColor=white[Docker]

== Architecture

This is a *single-module project* with two targets:

=== JavaScript - Kobweb Frontend

* *Location*: `site/src/jsMain`
* Compiles to JavaScript and fed to the backend
* Includes an "admin" section for managing content from the backend

=== JVM - http4k Backend

* *Location*: `site/src/jvmMain`
* Chosen over Kobweb's built-in Ktor server for more control + better syntax
* Serves the frontend files while providing the API endpoints

== Project Setup

=== Docker
* Use the provided `docker-compose.yml` as a base through GitHub or use
the https://hub.docker.com/repository/docker/maleficmarauder/guptarealty[maleficmarauder/guptarealty] image from Docker Hub.
* Much simpler setup, though with a lot less options for configuration

=== Git
* Clone the repo and open in IntelliJ IDEA or Android Studio
* Provides more control than the Docker setup, such as the ability to edit Kobweb site settings

== Declarations

* This project has minimal AI usage, though mostly just for tedious tasks and refactoring. All AI-generated code is reviewed and edited by me, so it should be up to reasonable standards.

== License
* This project is licensed under the MIT License. See the link:LICENSE[] file for details.
